M48
; DRILL file {KiCad 6.0.1-79c1e3a40b~116~ubuntu21.04.1} date Thu 24 Mar 2022 20:17:49
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-24T20:17:49+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.1-79c1e3a40b~116~ubuntu21.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
%
G90
G05
T1
X0.9922Y-0.9981
X1.1497Y-0.9981
T0
M30
